### ISSUE TITLE
Add "support" for foldername-tabs?

### ISSUE THREAD

**Issue by kankaristo** [ericcornelissen/pinned-tabs-for-atom#11]
Just found this package today and I like it a lot! I always wondered why this wasn't in Atom, since it's based on Chromium.

I also use [foldername-tabs](https://atom.io/packages/foldername-tabs), but the folder name isn't hidden when I pin the tab:
![screenshot from 2016-02-02 10-02-51](https://cloud.githubusercontent.com/assets/3522333/12743120/3eb67474-c994-11e5-9024-dc1e1b748b31.png) ![screenshot from 2016-02-02 10-03-18](https://cloud.githubusercontent.com/assets/3522333/12743122/42a4557e-c994-11e5-9a75-93a1b73a5c21.png)

This can fixed with just CSS, which shouldn't break anything even if you don't have foldername-tabs installed:
```css
.tab.pinned .folder {
    display: none;
}
```

I've added the above to my style sheet, but it would be nice to have straight in pinned-tabs.

**Comment by jerone** [comment]
This looks [more](https://github.com/ericcornelissen/pinned-tabs-for-atom/issues/8) like a combination of [foldername-tabs](https://atom.io/packages/foldername-tabs) begin pinned by [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom), which doesn't work on your theme. Which theme are you using? [Material UI](https://github.com/silvestreh/atom-material-ui) theme works great with both packages.

**Comment by kankaristo** [comment]
Ah yeah, sorry... I'm using the default Atom Dark UI theme, but I have some custom styling on the tabs, which seems to mess this up somehow.

I should have tested this a bit more before creating an issue. Closing. :smile:
