### ISSUE TITLE
Conflict with Nucleus Dark UI

### ISSUE THREAD

**Issue by onetrev** [ericcornelissen/pinned-tabs-for-atom#14]
Seems like Pinned Tabs is no longer working with Nucleus Dark UI https://atom.io/themes/nucleus-dark-ui.

Definitely used to work, but no longer does. If I pin the tab in One Dark UI first it seems to still work if I switch to Nucleus, but definitely does not seems to work if there are no pinned tabs and you try to pin one while using Nucleus Dark UI.

Thanks!

**Comment by ericcornelissen** [comment]
Thank you for pointing this out! I kinda fixed this issue :smile: However when all active tabs are pinned, the pinned effect is gone (see gif below, I'm not sure if this was the case before). This is of course not how it should be, but do you know if this bug existed before ?

![preview](http://i.imgur.com/U7P7MWR.gif)

**Comment by onetrev** [comment]
Hmm that makes sense. Must have been what I was trying to do. Unfortunately I can't say for sure if it existed before or is new. Seems like it must be new as I used the plugin few a good month or so and never noticed. But maybe just never tried to pinned all the tabs. Sorry I can't say 100% either way.

**Comment by ericcornelissen** [comment]
It has actually been there al along :open_mouth: However, for now it is hard to fix as (as far as I know) the desired effect is incompatible with the CSS of [Nucleus Dark UI](https://atom.io/themes/nucleus-dark-ui).
