### ISSUE TITLE
Issue with imdone-atom pinning

### ISSUE THREAD

**Issue by onetrev** [ericcornelissen/pinned-tabs-for-atom#15]
Pretty sure this is 100% replicate-able.... 

If you pin the tab you get if you pull up you imdone-atom list with this package: https://atom.io/packages/imdone-atom, then close Atom, the next time you open Atom, the imdone pinned tab is replaced with whatever was immediately to the right of it. Hope that makes sense!

**Comment by ericcornelissen** [comment]
I think it made sense, but I was not able to replicate it... What OS and version of Atom are you running, and what other packages? (maybe you can make a .gif of how to duplicate this bug)

**Comment by onetrev** [comment]
Hello! So just to start off with I wanted to make sure you tested with using Imdone-Atom package? No worries though I made a video that should show you exactly what's happening. You'll see how when I reload the tab to the right of my Imdone tab takes it over the tab. Please view here:

https://www.dropbox.com/s/eezceccygh7l03s/Recording%20%2346.mp4?dl=0

System Details:
Windows 10
Atom 1.7.2

```
packages: [
  "atom-beautify"
  "atom-css-unit-converter"
  "autocomplete-sass"
  "autocomplete-wordpress-hooks"
  "autoprefixer"
  "clipboard-history"
  "code-macro"
  "docblockr"
  "emmet"
  "file-icons"
  "flex-tool-bar"
  "git-diff-details"
  "git-time-machine"
  "imdone-atom"
  "javascript-snippets"
  "jquery-snippets"
  "language-diff"
  "linter"
  "linter-jshint"
  "linter-php"
  "minimap"
  "pacific-dark"
  "package-sync"
  "pigments"
  "pinned-tabs"
  "project-manager"
  "symbols-tree-view"
  "tool-bar"
  "wordpress-dictionary"
]
```

**Comment by ericcornelissen** [comment]
Hmm, I think I know what the problem is, but I still can't reproduce it. It seems that the Tasks tab from the imdone-atom package is closed when you exit Atom, but this doesn't happen on my system, do you have any clue why that happens on your computer? Anyway I should be able to fix this, but it will be quite a challenge to do...

**Comment by onetrev** [comment]
Oh my! Yeah sorry I never noticed the imdone-atom tab closes regardless of being pinned or not. My bad. So really I don't think this is an issue for Pinned Tabs. Weird it doesn't happen for you but if anything seems to be an issue with that package. So probably not worth your time. Sorry about that!
