### ISSUE TITLE
Atom Dark UI Error

### ISSUE THREAD

**Issue by ChristopherFunk** [ericcornelissen/pinned-tabs-for-atom#16]
On Windows 8.1 x64, Atom 1.7.4, using the Atom Dark theme, this happens:
![ui-error2](https://cloud.githubusercontent.com/assets/8630493/15653390/6881d724-2652-11e6-9a62-48d083e7805d.png)
Note the boxes between the tabs.
It does work properly with the One Dark theme however.
I haven't tested it on Linux yet.

I had also restarted Atom and the bug was still present.

**Comment by ericcornelissen** [comment]
Thanks for pointing this out, it was caused by a style rule that was not relevant anymore anyway so it was an easy fix :smiley: (However, I did discover another bug with Atom Dark theme, which was a little harder to fix :grin:)
