### ISSUE TITLE
Pinned Tab Not reducing Size

### ISSUE THREAD

**Issue by craigiswayne** [ericcornelissen/pinned-tabs-for-atom#17]
Attached below is a screencast of the action.

The Tab "pins" itself, well moves to the front of the line but the actual tab (not the pane) does not reduce in size, so the whole file name is visible.

If you require any additional information (i'm sure you do) please let me know.

[screencast 2016-05-31 08-11-03.mp4.zip](https://github.com/ericcornelissen/pinned-tabs-for-atom/files/290428/screencast.2016-05-31.08-11-03.mp4.zip)

**Comment by ericcornelissen** [comment]
I would indeed like some additional information, as I'm unable to reproduce the bug :) Could you give me the packages and themes you're using?

Also, did you use this package before update [v0.2.3](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v0.2.3)? If so, I assume the bug wasn't there before...

**Comment by craigiswayne** [comment]
Below is the output of apm list.

`Built-in Atom Packages (89)
├── about@1.4.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.1
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.2
├── bracket-matcher@0.81.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.25.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.1
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.0
├── language-css@0.36.0
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.17.6
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.3
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.1
├── line-ending-selector@0.3.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.2.0
├── one-light-syntax@1.2.0
├── one-light-ui@1.2.0
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.1
├── solarized-dark-syntax@1.0.0
├── solarized-light-syntax@1.0.0
├── spell-check@0.67.0
├── status-bar@1.1.2
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (13) /Users/craigiswayne/.atom/packages
├── atom-beautify@0.29.7
├── atom-minify@0.7.3
├── file-icons@1.7.13
├── git-projects@1.17.0
├── html-entities@0.4.0
├── markdown-preview-plus@2.4.0
├── open-recent@5.0.0
├── php-debug@0.2.3
├── pinned-tabs@0.2.3
├── sass-autocompile@0.12.6
├── tablr@1.3.1
├── terminal-plus@0.14.5
└── todo-show@1.6.0

└── (empty)`

haven't installed any extra themes. I'm currently using **One Dark** for both the UI and Syntax.

I've had this package for a while, and i think you're right, it did work before.

Additionally, running Mac OSX El Capitan.

**Comment by ericcornelissen** [comment]
Un

**Comment by craigiswayne** [comment]
this is so weird, as you previously saw, the tabs were not changing in size, now they do.

this is all i did

Preferences > Open Config Folder > packages > pinned-tabs > styles

added in an arbitrary style, saved

pinned a tab, worked as expected.

removed the arbitrary style. saved.... still working as expected. 

Sorry for wasting your time @ericcornelissen

**Comment by ericcornelissen** [comment]
That's weird indeed... anyway, its not a problem, I'm glad its working now! :)
