### ISSUE TITLE
Prevent closing a pinned tab

### ISSUE THREAD

**Issue by jmdacruz** [ericcornelissen/pinned-tabs-for-atom#20]
It would be nice to have a configuration to be able to prevent closing pinned tabs when doing "Close All Tabs"

**Comment by aewing** [comment]
+1

**Comment by ericcornelissen** [comment]
Great idea! I will look into this when issue #21 is closed :smile:

**Comment by ericcornelissen** [comment]
As of now it is not possible to prevent a tab from closing after "Close All Tabs" has been initiated, I've opened an issue at Atom repository requesting for a feature that would allow for your request to be added. I'll keep this issue updated on the progress and will implement the feature as soon as possible :smile:

**Comment by rgauci** [comment]
I'd also love to have _Close all but pinned_ functionality! Any updates on this, please?

**Comment by ericcornelissen** [comment]
@rgauci, this is already part of the package but it is disabled by default 😄

Just go to the settings of the package and check the `Enable the 'Close Unpinned Tabs' option` checkbox. It'll add an option to the right-click menu of any tab with the text "Close Unpinned Tabs"

![option](https://user-images.githubusercontent.com/3742559/27878018-1f729490-61bd-11e7-80d2-ec0337f4ee04.JPG)

**Comment by rgauci** [comment]
Love it, thanks!

**Comment by xixixao** [comment]
Looks like this task can be closed now .)
