### ISSUE TITLE
No icon when when file hasn't been saved

### ISSUE THREAD

**Issue by epelc** [ericcornelissen/pinned-tabs-for-atom#24]
The pinned tabs show as a blank space if the file hasn't been saved yet.

When it is active
![image](https://cloud.githubusercontent.com/assets/5204642/18523338/d6e1b2a6-7a81-11e6-8d98-e06f7bab980b.png)

It is blank when the pinned tab is not active
![image](https://cloud.githubusercontent.com/assets/5204642/18523460/5286c84c-7a82-11e6-85ed-a9218b9d2a21.png)

**Comment by ericcornelissen** [comment]
Thank you for reporting! I fixed the issue (e841606155593b1cf08ad5f1eb517680cba032dc) and published an update :smile:
