### ISSUE TITLE
Add support for git-control

### ISSUE THREAD

**Issue by Wombosvideo** [ericcornelissen/pinned-tabs-for-atom#26]
Please add icon support for the git-control package. By default it doesn't have one but it would be nice if it had a GIT icon **when pinned**

[Atom git-control package](https://atom.io/packages/git-control)

**Comment by ericcornelissen** [comment]
I think it is better if the icon would be provided by another package, such as [file-icons](https://atom.io/packages/file-icons). However, the git-control package is not implemented such that file-icons can give it an icon. I will go ahead and try to get both packages to update their code to support this if you want.

Also, is their any particular reason why you said __when pinned__ (in bold)? Is it really necessary that the icon is not there when it is not pinned? And in that case, would it be an idea to add an option to this package to hide icons when the tab is not pinned?

**Comment by Wombosvideo** [comment]
> I will go ahead and try to get both packages to update their code to support this if you want.

Great
> Is it really necessary that the icon is not there when it is not pinned?

No it's not but since it only has one when pinned I thought... Well... scrap it and show the icon all the time. Don't know why I put it in bold
> And in that case, would it be an idea to add an option to this package to hide icons when the tab is not pinned?

I wouldn't personally use this option but I think it could be quite useful when having many tabs open so you have more space for the text label. Yes, if possible, add this functionality.

**Comment by ericcornelissen** [comment]
@Wombosvideo, do you still want this feature? Given that with [Atom 1.18](http://blog.atom.io/2017/06/13/atom-1-18.html) there is git control build into Atom, and given that the atom-git-control repository seems to have been [abandoned](https://github.com/jacogr/atom-git-control/issues/233)...

If not I'll close this issue 🙂

**Comment by ericcornelissen** [comment]
It seems the atom-git-control repo has lost interest again... I will close this issue for now, any further remarks @Wombosvideo?

**Comment by Wombosvideo** [comment]
No, this is fine. I don't use that plugin very often anymore
