### ISSUE TITLE
Icons Now Disappeared

### ISSUE THREAD

**Issue by craighooghiem** [ericcornelissen/pinned-tabs-for-atom#28]
Atom: 1.16.0
Pinned Tabs: 1.0.0

Before installing file-icons, there no tab icons anymore. 
I have installed file-icons, but would be nice if there was a fallback for those who are updating and not reading the entire readme.

![image](https://cloud.githubusercontent.com/assets/1476306/25780640/ea00fa4c-32f8-11e7-8d15-a6c5fcc5715e.png)

**Comment by ericcornelissen** [comment]
Thanks for reporting, forgot to test that before releasing the new version 😅 I'll publish a fix later today!
