### ISSUE TITLE
No Icons are displayed on Linux for pinned tabs

### ISSUE THREAD

**Issue by michael-nischt** [ericcornelissen/pinned-tabs-for-atom#32]
It used to work with packages like
* file-icons
* seti-icons

but doesn't anymore.

**Comment by AntonioRedondo** [comment]
Yes, this also happens on macOS and Windows since Atom new version 1.17.

**Comment by ericcornelissen** [comment]
Sorry for not responding 😅

Thanks for reporting, I had the issue myself (on Windows) as well. I just published a new version that should fix this issue!
