### ISSUE TITLE
Adds weird unstyled icons to the tab bar

### ISSUE THREAD

**Issue by bryan-havenly** [ericcornelissen/pinned-tabs-for-atom#36]
I just installed this package and it added icons to my tab bar that I don't want. I went to hide them with CSS but they seem to somehow not appear in the DOM for the tabs.

<img width="551" alt="screen shot 2017-08-02 at 9 09 46 am" src="https://user-images.githubusercontent.com/26387741/28880505-803bf748-7762-11e7-8496-0341c8c46126.png">

Here's a screenshot of the inspector for the above tab
<img width="513" alt="screen shot 2017-08-02 at 9 11 20 am" src="https://user-images.githubusercontent.com/26387741/28880573-ba2b91a2-7762-11e7-94a6-bf850012939b.png">

I'm not sure how to give reproduction steps because this happened for me by just installing `pinned-tabs`. I'm not using any other packages that provide tabs or icons besides the core `tabs` package. (Maybe it's useful to note that I don't have the `file-icons` package installed?) The theme I'm running is `One Light`, with no custom CSS at all.

**Comment by bryan-havenly** [comment]
Update: The icons are actually for the _next_ tab, not the current one. I was able to hide them with this CSS:

`
// Disable icons from pinned tabs
.tab-bar .texteditor.tab .title:before {
  display: none;
}
`

**Comment by ericcornelissen** [comment]
Thank you for reporting. Especially thanks for specifying the them you're using and saying that you're not using file-icons, that helps a ton 👍 I'll try to look into this and release a solution as soon as possible!

**Comment by ericcornelissen** [comment]
Thank you for reporting. And especially thanks for mentioning what theme you're running and that you don't have file-icons installed 👍

I'm glad you where able to solve this problem for yourself. Still, I'm going to try to fix the issue so it works correctly by default 🙂

**Comment by bryan-havenly** [comment]
Final update:

The only issue here is that file icons get added for unpinned tabs. Changing the selector for icons from `.tab-bar .tab .title:before` to `.tab-bar .tab.pinned .title:before` seems to be the solution. I'll work up a PR if I have time today.

**Comment by ericcornelissen** [comment]
Great! Thank you for find out what was wrong 😄
