### ISSUE TITLE
Duplicate Icons in tabs/panes

### ISSUE THREAD

**Issue by Gunny123** [ericcornelissen/pinned-tabs-for-atom#4]
I don't think this is intended behavior. See my screen cast <a href="http://gfycat.com/NastyLankyIrishterrier" target="_blank">here</a>. Seems that it is taking the next tab icon on hover. Disabling the plugin solves the issue.

**Comment by ericcornelissen** [comment]
It sure isn't, can you tell me what other packages you're using, that might help me debugging.

**Comment by Gunny123** [comment]
I am using the Native UI theme w/ GI Light Syntax.  

Currently using:

open-recent
aligner
atom-beautify
atom-html-preview
autoclose-html
color picker
emmet
file-icons
language-swift
minimap
pigments
pinned-tabs (disabled at the moment)

<a href="http://imgur.com/a/gZHIF" target="_blank">I took screenshots of all my current packages also</a>

**Comment by ericcornelissen** [comment]
Thanks, the problem was the Native UI theme :) I fixed the problem and published it to APM!

**Comment by Gunny123** [comment]
Nice work!
