### ISSUE TITLE
Use of the .pinned class causes issues with Zentabs

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/pinned-tabs-for-atom#44]
As pointed out by @brettz9 in #33, it seems that the use of the class `.pinned` causes issues when one is also using the [zentabs](https://atom.io/packages/zentabs) package

**Comment by brettz9** [comment]
The README speaking about custom styling should also be updated to use `pinned-tabs` instead of `pinned`.

**Comment by brettz9** [comment]
Sorry, corrected post just now to say `pinned-tab`.

**Comment by ericcornelissen** [comment]
Of course 😅
