### ISSUE TITLE
Feature request: pin pending item

### ISSUE THREAD

**Issue by Jackymancs4** [ericcornelissen/pinned-tabs-for-atom#47]
Hello @ericcornelissen 

The problem is that if I pin a pending item (the items with italic titles formerly known as preview items) and then open a new file with the tree view, the pinned item get replaced by the new one (unpinned).

It's a little bothering having to check every time by double clicking the title.

I tried to look for a solution but I wasn't able to find any official API for this.
So, I'm not sure if you can activate a pending item from your package or you need to close and reopen it as an activated one.

The behavior that I think is more correct is that pinning an item should also confirm it. 

For references:
https://flight-manual.atom.io/using-atom/sections/pending-pane-items/

Thank you!

**Comment by ericcornelissen** [comment]
Thank your for the suggestion @Jackymancs4, it makes sense to me. I can't remember ever having this issue, even though I have pending-pane-items enabled 🤔 Anyway I'll see if I can implement something!

**Comment by ericcornelissen** [comment]
I'm sorry it took a while, but I published a fix with release [v2.0.6](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v2.0.6). Feel free to reopen this issue if the problem persists 🙂
