### ISSUE TITLE
Is there a way to reduce start up time?

### ISSUE THREAD

**Issue by Gunny123** [ericcornelissen/pinned-tabs-for-atom#5]
I noticed the package adds 271ms to start up time. Is there a way to reduce this? A lot of the other community packages I have installed have a start up time less than ~85ms.

**Comment by ericcornelissen** [comment]
I did notice this when I started this package, but ignored it then and figured I would have a look at it later. Its good that you point it out though. However, after I changed a few things after v0.1.7 I had a look at this and Atom said pinned-tabs added only ~20ms to the startup time...

I just published a new version to APM, try downloading it and let me know if the start up time is still bad on your machine after that.

**Comment by Gunny123** [comment]
Boss. 17ms startup time. Looks good to me!

**Comment by ericcornelissen** [comment]
Nice! Honestly, I have no idea how I managed to get it down at all :sweat_smile:
