### ISSUE TITLE
Graphical Issue with file-icons color mode off

### ISSUE THREAD

**Issue by HintonR** [ericcornelissen/pinned-tabs-for-atom#53]
There is a graphical error occurring on pinned tabs when file-icon package option is ticked off for color.

**Comment by ericcornelissen** [comment]
Thanks for the report @HintonR, I will try to find a solution as soon as possible!

**Comment by ericcornelissen** [comment]
Should be fixed now with [the release of v2.1.2](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v2.1.2).
