### ISSUE TITLE
Add new demo loop

### ISSUE THREAD

**Issue by Gunny123** [ericcornelissen/pinned-tabs-for-atom#6]
I made a demo loop to showcase the package in action. I think it may look a little better. 

<blockquote class="imgur-embed-pub" lang="en" data-id="gmytTjF"><a href="//imgur.com/gmytTjF">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

<a href="http://gfycat.com/NeedyTatteredArgentinehornedfrog" target="_blank">View it here on Gfycat</a>

<a href="https://drive.google.com/file/d/0Bxd5qn5MQhKgaVh0UGRwRkpkLXM/view?usp=sharing" target="_blank">Short version on Google Drive</a>

<a href="https://drive.google.com/file/d/0Bxd5qn5MQhKgUTBmRm8xSFk3V3M/view?usp=sharing" target="_blank">Even here for the full length.</a>

**Comment by ericcornelissen** [comment]
I appreciate the effort, but would you mind telling me what the main difference is between this one and the one currently used in README.md ?

I personally prefer the one I'm currently using, so if you tell me what you would prefer to see in the demo, I can re-record and update it. (I have to update it anyways, so any feedback is welcome :smile:)

**Comment by Gunny123** [comment]
I just thought that it gave a better representation with the full editor displayed.

**Comment by ericcornelissen** [comment]
I personally dislike displaying the full editor, because it doesn't add any value in my opinion :sweat_smile: Could you elaborate more on why you think it gives a better representation ?

**Comment by Gunny123** [comment]
I think that it adds more depth and visual compared to just the tabs themselves. Maybe I'm just blowing smoke and I realize its your baby, but I think that giving a full perspective gives the user a more real world use.

**Comment by ericcornelissen** [comment]
I will certainly make a demo in both ways for the next update, so I can compare it  a litte bit better :smile:

**Comment by Gunny123** [comment]
Okay. Sounds good.

**Comment by ericcornelissen** [comment]
I've got a [small version](http://i.imgur.com/VPIvo4p.gif) and a [big version](http://i.imgur.com/MaJkSvR.gif), tell me what you think :smile:

**Comment by Gunny123** [comment]
BIG!

**Comment by ericcornelissen** [comment]
I'm sorry but I've decided to go for the small version... :worried: But still, thanks for the effort!
