### ISSUE TITLE
Every CSS property is forced with !important

### ISSUE THREAD

**Issue by jerone** [ericcornelissen/pinned-tabs-for-atom#7]
To play nice with other packages and themes it isn't a good idea to force every CSS property in this package with `!important`. With better selectors it's also possible to apply the correct styles: https://gist.github.com/jerone/f4685bcd97d7fb7dbcde

Two examples where forcing CSS is conflicting with is <sub>(my)</sub> [atom-new-tab](https://github.com/jerone/atom-new-tab) package and [atom-material-ui](https://github.com/silvestreh/atom-material-ui) theme.

I hope you can fix this. Great package!

_Atom 1.5.0-beta0
Pinned-tabs 0.1.9
New-tab 0.4.1
Material-ui 0.8.0_

**Comment by ericcornelissen** [comment]
I will have a look into this! And thanks for the [link](https://gist.github.com/jerone/f4685bcd97d7fb7dbcde) :smile:

**Comment by ericcornelissen** [comment]
I was unable to remove all (actually most...) uses of ```!important```. However, I reduced the use of ```!important``` that impacts other packages/themes. I also tested it for the [atom-new-tab](https://github.com/jerone/atom-new-tab) package and [atom-material-ui](https://github.com/silvestreh/atom-material-ui) theme. Would you mind cloning this package onto your machine and test it (before I publish the update to APM) ?

**Comment by jerone** [comment]
Just tested it and seems to be compatible now :+1: :shipit:

**Comment by ericcornelissen** [comment]
Nice, I'll be publishing it soon :+1:
