### ISSUE TITLE
Incompatible with foldername-tabs

### ISSUE THREAD

**Issue by jerone** [ericcornelissen/pinned-tabs-for-atom#8]
As this is a newer package I'm reporting this here...

This package seems incompatible with [foldername-tabs](https://atom.io/packages/foldername-tabs) package, when a tab is unpinned again.

**Steps to reproduce:**

1. Install both this package and foldername-tabs: `apm install pinned-tabs foldername-tabs`
2. Open a file and pin the tab.
3. Unpin the same tab and see that foldername-tabs isn't working on that tab.

I'm hoping you can find a fix for this here or propose a solution at https://github.com/paulpflug/foldername-tabs

_Atom 1.5.0-beta0
Pinned-tabs 0.1.9
Foldername-tabs 0.1.6_

**Comment by ericcornelissen** [comment]
I will see what I can do about this! Thanks for reporting the bug.

**Comment by ericcornelissen** [comment]
Unfortunately this is due to a bug with that package ([foldername-tabs](https://atom.io/packages/foldername-tabs)). Have a look at [this](https://github.com/paulpflug/foldername-tabs/issues/4) issue. To pin a tab, this package uses the same mechanism as dragging and dropping.

**Comment by jerone** [comment]
This seems to be solved when https://github.com/paulpflug/foldername-tabs/issues/4 was fixed.
